/se-connecter:
  controller: "User"
  action: "login"

/se-deconnecter:
  controller: "User"
  action: "logout"

/backoffice:
  controller: "Backoffice"
  action: "dashboard"

/page:
  controller: "page"
  action: "show"

/home:
  controller: "Home"
  action: "home"